from taipy import Gui
import numpy as np
import pandas as pd
from utils import load_krp_file, get_laps


def load_telemetry_file(state):
    fname = state.fname
    state.df_head, state.df_units, state.df, state.laptimes = load_krp_file(fname)
    state.df_head = state.df_head.reset_index()
    state.df_units = state.df_units.reset_index()
    state.df = state.df.reset_index()
    state.laptimes = state.laptimes.reset_index()

    state.df_disp = state.df.copy()
    # state.df_disp.index = (state.df_disp.index - pd.to_datetime(0)).total_seconds()
    state.df_disp["Time"] = (
        state.df_disp["Time"] - pd.to_datetime(0)
    ).dt.total_seconds()
    state.laps = list(get_laps(state.df))


fname = ""
df_head = pd.DataFrame(columns=["key", "value"])
df_units = pd.DataFrame(columns=["index", "units"])
df = pd.DataFrame(
    columns=[
        "Time",
        "Distance",
        "Engine",
        "CylHeadTemp",
        "WaterTemp",
        "Gear",
        "Speed",
        "LatAcc",
        "LonAcc",
        "Steer",
        "Throttle",
        "Brake",
        "FrontBrakes",
        "Clutch",
        "YawVel",
        "PosX",
        "PosY",
        "Lap",
        "Starttime",
        "Laptime",
    ]
)
laptimes = pd.DataFrame(columns=["Lap", "Laptime"])
laps = []
lap_sel = []
df_disp = None

# fname = "Logdata Essay mini60 2023-10-31.csv"
# df_head, df_units, df, laptimes = load_krp_file(fname)
# laps = get_laps(df)
# selected_laps = pd.Series(True, index=laps)
# df_disp = df.copy()
# df_disp.index = (df_disp.index - pd.to_datetime(0)).total_seconds()


head = """
<|{fname}|file_selector|label=Open Kart Racing Pro Telemetry File|on_action=load_telemetry_file|extensions=.csv|drop_message=Drop Message|>

<|navbar|>
"""

# ToFix format: <|{laptimes}|table|rebuild|columns={"Laptime": {"format": "%.3f"}}|page_size=5|>

laptime_cols = {"Laptime": {"format": "%.3f"}}
data_cols = {"Time": {"format": "%.3f"}, "Laptime": {"format": "%.3f"}}

page_data = """
<|layout|columns=40% 30% 30%|

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>


<|{df_disp}|table|rebuild|columns={data_cols}|>
"""


page_analyse = """
<|layout|columns=40% 30% 30%|

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>

<|{lap_sel}|selector|multiple|lov={laps}|>

<|layout|columns=70% 30%|
<|{df}|chart|mode=line|x=Distance|y=Engine|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=CylHeadTemp|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=WaterTemp|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Gear|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Speed|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=LatAcc|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=LonAcc|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Steer|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Throttle|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Brake|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=FrontBrakes|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=Clutch|color=Lap|>
<|{df}|chart|mode=line|x=Distance|y=YawVel|color=Lap|>

<|{df}|chart|mode=scatter|x=PosX|y=PosY|>

|>
"""

page_laps = """
<|layout|columns=60% 40%|

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=20|>

<|{df_head}|table|rebuild|page_size=20|>

|>

"""

page_rpm_hist = """
<|layout|columns=40% 30% 30%|

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>



"""

page_about = """
# Kart Racing Pro Telemetry analyser

Analyse the telemetry data generated by the karting simulator [Kart Racing Pro](https://www.kartracing-pro.com/).

To run the program press "Open Kart Racing Pro Telemetry File" and then select the file created by Kart Racing Pro.

You don't own KRP? Use this [sample file](https://raw.githubusercontent.com/scls19fr/krp_python_telemetry/taipy/Logdata%20Essay%20mini60%202023-10-31.csv).

The tabs are:

 * **About** information of the tool
 * **Data** to view table data of speed, throttle, break, steer etc
 * **Analyse** to view graphs of speed, throttle, break, steer etc
 * **Laps** to show only lap times

All graphs including the track map is zoomable.

Feel free to watch code at [https://github.com/scls19fr/krp_python_telemetry](https://github.com/scls19fr/krp_python_telemetry)
"""

pages = {
    "/": head,
    "about": page_about,
    "data": page_data,
    "analyse": page_analyse,
    "laps": page_laps,
    # "rpm hist": page_rpm_hist,
}

if __name__ == "__main__":
    gui = Gui(pages=pages)
    gui.run(dark_mode=False)
