from taipy import Gui
import numpy as np
import pandas as pd
from utils import load_krp_file, get_laps


def load_telemetry_file(state):
    fname = state.fname
    state.df_head, state.df_units, state.df_all, state.laptimes = load_krp_file(fname)
    state.df_head = state.df_head.reset_index()
    state.df_units = state.df_units.reset_index()
    state.df_all = state.df_all.reset_index()
    state.laptimes = state.laptimes.reset_index()

    state.laps = list(get_laps(state.df_all))
    state.laps = [str(lap) for lap in state.laps]

    selected_laps = []
    state.df = filtering_laps(state.df_all, selected_laps)

    state.df_disp = state.df_all.copy()

    # state.df_disp.index = (state.df_disp.index - pd.to_datetime(0)).total_seconds()

    state.df_disp["Time"] = (
        state.df_disp["Time"] - pd.to_datetime(0)
    ).dt.total_seconds()


def filtering_laps(df: pd.DataFrame, selected_laps):
    df_filtered = df[df["Lap"].map(lambda lap: lap in selected_laps)]
    return df_filtered


def filter_by_laps(state):
    selected_laps = [int(lap) for lap in state.lap_sel]
    state.df = filtering_laps(state.df_all, selected_laps)


fname = ""
df_head = pd.DataFrame(columns=["Key", "Value"])
df_units = pd.DataFrame(columns=["Data", "Units"])
df_all = pd.DataFrame(
    columns=[
        "Time",
        "Distance",
        "Engine",
        "CylHeadTemp",
        "WaterTemp",
        "Gear",
        "Speed",
        "LatAcc",
        "LonAcc",
        "Steer",
        "Throttle",
        "Brake",
        "FrontBrakes",
        "Clutch",
        "YawVel",
        "PosX",
        "PosY",
        "Lap",
        "Starttime",
        "Laptime",
    ]
)
laptimes = pd.DataFrame(columns=["Lap", "Laptime"])
laps = []
lap_sel = []
df = df_all.copy()
df_disp = df_all.copy()


head = """
<|{fname}|file_selector|label=Open Kart Racing Pro Telemetry File|on_action=load_telemetry_file|extensions=.csv|drop_message=Drop Message|>

<|navbar|>
"""

laptime_cols = {"Lap": {}, "Laptime": {"format": "%.3f"}}

data_cols = {}
for col in df.columns:
    data_cols[col] = {}
for col in ["Time", "Laptime"]:
    data_cols[col] = {"format": "%.3f"}

page_data = """
<|layout|columns=40% 30% 30%|

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>


<|{df_disp}|table|rebuild|columns={data_cols}|>
"""


page_analyse = """
<|layout|columns=15% 30% 25% 25%|

<|{lap_sel}|selector|multiple|lov={laps}|height=300px|on_change=filter_by_laps|>

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>

<|layout|columns=70% 30%|
<|{df}|chart|mode=line|x=Distance|y=Engine|>
<|{df}|chart|mode=line|x=Distance|y=CylHeadTemp|>
<|{df}|chart|mode=line|x=Distance|y=WaterTemp|>
<|{df}|chart|mode=line|x=Distance|y=Gear|>
<|{df}|chart|mode=line|x=Distance|y=Speed|>
<|{df}|chart|mode=line|x=Distance|y=LatAcc|>
<|{df}|chart|mode=line|x=Distance|y=LonAcc|>
<|{df}|chart|mode=line|x=Distance|y=Steer|>
<|{df}|chart|mode=line|x=Distance|y=Throttle|>
<|{df}|chart|mode=line|x=Distance|y=Brake|>
<|{df}|chart|mode=line|x=Distance|y=FrontBrakes|>
<|{df}|chart|mode=line|x=Distance|y=Clutch|>
<|{df}|chart|mode=line|x=Distance|y=YawVel|>

<|{df}|chart|mode=scatter|x=PosX|y=PosY|>

|>
"""

page_laps = """
<|layout|columns=60% 40%|

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=20|>

<|{df_head}|table|rebuild|page_size=20|>

|>

"""

page_rpm_hist = """
<|layout|columns=40% 30% 30%|

<|{df_head}|table|rebuild|page_size=5|>

<|{laptimes}|table|rebuild|columns={laptime_cols}|page_size=5|>

<|{df_units}|table|rebuild|page_size=5|>

|>



"""

page_about = """
# Kart Racing Pro Telemetry analyser

Analyse the telemetry data generated by the karting simulator [Kart Racing Pro](https://www.kartracing-pro.com/).

To run the program press "Open Kart Racing Pro Telemetry File" and then select the file created by Kart Racing Pro.

You don't own KRP? Use this [sample file](https://raw.githubusercontent.com/scls19fr/krp_python_telemetry/taipy/Logdata%20Essay%20mini60%202023-10-31.csv).

The tabs are:

 * **About** information of the tool
 * **Data** to view table data of speed, throttle, break, steer etc
 * **Analyse** to view graphs of speed, throttle, break, steer etc
 * **Laps** to show only lap times

All graphs including the track map is zoomable.

Feel free to watch code at [https://github.com/scls19fr/krp_python_telemetry](https://github.com/scls19fr/krp_python_telemetry)
"""

pages = {
    "/": head,
    "about": page_about,
    "data": page_data,
    "analyse": page_analyse,
    "laps": page_laps,
    # "rpm hist": page_rpm_hist,
}

if __name__ == "__main__":
    gui = Gui(pages=pages)
    gui.run(title="KRP Telemetry", dark_mode=False)
